spring:
  profiles:
    active: dev
<<<<<<< HEAD

=======
>>>>>>> upstream/stu_dev_0809
mybatis:
  mapper-locations: classpath*:com/gpmall/order/dal/persistence/*Mapper.xml"
  type-aliases-package: com.gpmall.order.dal.entitys
